apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: pomodoro-pgadmin
    namespace: pomodoro-services
    labels:
      env: development
  spec:
    containers:
    - name: pomodoro-pgadmin
      image: localhost:32000/pomodoro-pgadmin
      env:
      - name: PGADMIN_DEFAULT_EMAIL
        value: user@domain.com
      - name: PGADMIN_DEFAULT_PASSWORD
        value: Password1
      imagePullPolicy: IfNotPresent
    restartPolicy: Always 
- apiVersion: v1
  kind: Service
  metadata:
    name: pomodoro-pgadmin
    namespace: pomodoro-services
  spec:
    type: NodePort
    ports:
    - port: 5002
      targetPort: 80
    selector:
        app: pomodoro-pgadmin
        env: development
