apiVersion: v1
kind: Service
metadata:
  name: pomodoro-ping-rapi
  namespace: pomodoro-services
spec:
  ports:
  - port: 8888
    targetPort: 80
  selector:
      app: pomodoro-ping-rapi
      env: development
