apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pomodoro-pgsql-pv-a
  spec:
    capacity: 
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
      - ReadOnlyMany
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: /tmp/pomodoro-pgsql
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pomodoro-pgsql-pv-b
  spec:
    capacity: 
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
      - ReadOnlyMany
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: /tmp/pomodoro-pgsql
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pomodoro-pgsql-pv-c
  spec:
    capacity: 
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
      - ReadOnlyMany
    persistentVolumeReclaimPolicy: Retain
    hostPath:
      path: /tmp/pomodoro-pgsql






