apiVersion: v1
kind: Pod
metadata:
  name: pomodoro-pgadmin
  namespace: pomodoro-services
  labels:
    env: development
spec:
  containers:
  - name: pomodoro-pgadmin
    image: localhost:32000/pomodoro-pgadmin
    env:
    - name: PGADMIN_DEFAULT_EMAIL
      value: user@domain.com
    - name: PGADMIN_DEFAULT_PASSWORD
      value: Password1
    imagePullPolicy: IfNotPresent
  restartPolicy: Always 
  