apiVersion: v1
kind: Pod
metadata:
  name: pomodoro-utils
  namespace: pomodoro-services
  labels:
    env: development
spec:
  containers:
  - name: pomodoro-utils
    image: localhost:32000/pomodoro-utils
    command:
      - sleep
      - "3000"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always 

